package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"subgraphsecond/graph/model"
)

// FindAccountByAccountReferenceID is the resolver for the findAccountByAccountReferenceID field.
func (r *entityResolver) FindAccountByAccountReferenceID(ctx context.Context, accountReferenceID string) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: FindAccountByAccountReferenceID - findAccountByAccountReferenceID"))
}

// FindCardByCardReferenceID is the resolver for the findCardByCardReferenceID field.
func (r *entityResolver) FindCardByCardReferenceID(ctx context.Context, cardReferenceID string) (*model.Card, error) {
	panic(fmt.Errorf("not implemented: FindCardByCardReferenceID - findCardByCardReferenceID"))
}

// FindTransactionByTransactionID is the resolver for the findTransactionByTransactionID field.
func (r *entityResolver) FindTransactionByTransactionID(ctx context.Context, transactionID string) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: FindTransactionByTransactionID - findTransactionByTransactionID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
