// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AvailableCreditAmount struct {
	SpendingCreditAmount *float64 `json:"spendingCreditAmount,omitempty"`
	CashCreditAmount     *float64 `json:"cashCreditAmount,omitempty"`
}

type Card struct {
	CardReferenceID string         `json:"cardReferenceId"`
	Status          *string        `json:"status,omitempty"`
	Type            *string        `json:"type,omitempty"`
	ExpiryDate      *string        `json:"expiryDate,omitempty"`
	CardNumber      *string        `json:"cardNumber,omitempty"`
	Transactions    []*Transaction `json:"transactions,omitempty"`
}

func (Card) IsEntity() {}

type Query struct {
}

type Transaction struct {
	TransactionID         string                 `json:"transactionId"`
	Amount                *float64               `json:"amount,omitempty"`
	Currency              *string                `json:"currency,omitempty"`
	Status                *string                `json:"status,omitempty"`
	TransactionDate       *string                `json:"transactionDate,omitempty"`
	AvailableCreditAmount *AvailableCreditAmount `json:"availableCreditAmount,omitempty"`
}

func (Transaction) IsEntity() {}
