// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	AccountReferenceID string `json:"accountReferenceId"`
}

func (Account) IsEntity() {}

type Customer struct {
	CustomerReferenceID string     `json:"customerReferenceId"`
	Name                string     `json:"name"`
	Last4ssn            string     `json:"last4ssn"`
	Age                 int32      `json:"age"`
	Address             string     `json:"address"`
	Email               string     `json:"email"`
	Accounts            []*Account `json:"accounts,omitempty"`
}

func (Customer) IsEntity() {}

type Query struct {
}

type Transaction struct {
	TransactionID string `json:"transactionId"`
}

func (Transaction) IsEntity() {}
