package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"subgraphfirst/graph/data"
	"subgraphfirst/graph/model"
)

// GetCustomers is the resolver for the getCustomers field.
func (r *queryResolver) GetCustomers(ctx context.Context) ([]*model.Customer, error) {
	return data.Customers(), nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	return data.Customers(), nil
}

// GetCustomer is the resolver for the getCustomer field.
func (r *queryResolver) GetCustomer(ctx context.Context, customerReferenceID string) (*model.Customer, error) {
	for _, customer := range data.Customers() {
		if customer.CustomerReferenceID == customerReferenceID {
			return customer, nil
		}
	}
	return nil, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
